[package]
name = "image-downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.18"
tokio = { version = "1", features = ["full"] }
tempfile = "3.2.0"
thiserror = "1.0.24"
anyhow = "1.0.40"
